/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as GenreIndexRouteImport } from './routes/genre/index'
import { Route as SeriesIdRouteImport } from './routes/series/$id'
import { Route as MovieIdRouteImport } from './routes/movie/$id'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreIndexRoute = GenreIndexRouteImport.update({
  id: '/genre/',
  path: '/genre/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/genre': typeof GenreIndexRoute
  '/home': typeof HomeIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/search': typeof SearchIndexRoute
  '/series': typeof SeriesIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/genre': typeof GenreIndexRoute
  '/home': typeof HomeIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/search': typeof SearchIndexRoute
  '/series': typeof SeriesIndexRoute
  '/watchlist': typeof WatchlistIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie/$id': typeof MovieIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/genre/': typeof GenreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie/$id'
    | '/series/$id'
    | '/genre'
    | '/home'
    | '/movies'
    | '/search'
    | '/series'
    | '/watchlist'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie/$id'
    | '/series/$id'
    | '/genre'
    | '/home'
    | '/movies'
    | '/search'
    | '/series'
    | '/watchlist'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/movie/$id'
    | '/series/$id'
    | '/genre/'
    | '/home/'
    | '/movies/'
    | '/search/'
    | '/series/'
    | '/watchlist/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieIdRoute: typeof MovieIdRoute
  SeriesIdRoute: typeof SeriesIdRoute
  GenreIndexRoute: typeof GenreIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/': {
      id: '/genre/'
      path: '/genre'
      fullPath: '/genre'
      preLoaderRoute: typeof GenreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieIdRoute: MovieIdRoute,
  SeriesIdRoute: SeriesIdRoute,
  GenreIndexRoute: GenreIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
